# Generated by Django 6.0.3 on 2026-06-17 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=4)),
                ('ratio_to_base', models.FloatField(default=1)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='configuration.unit')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configuration.unittype')),
            ],
        ),
    ]
