# Generated by Django 6.0.3 on 2026-06-27 02:35

from django.db import migrations


def populate_default_unit_type(apps, schema_editor):
    default_utype = ["Mass", "Volume", "Other"]
    utype = apps.get_model("configuration", "UnitType")

    utype.objects.bulk_create([
        utype(id=1, name=default_utype[0]),
        utype(id=2, name=default_utype[1]),
        utype(id=3, name=default_utype[2]),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_default_unit_type),
    ]

